# Generated by Django 5.1.4 on 2025-01-03 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del servicio (máximo 200 caracteres).', max_length=200, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('descripcion', models.TextField(help_text='Descripción detallada del servicio.')),
                ('imagen', models.ImageField(help_text='Imagen representativa del servicio (formatos permitidos: JPG, JPEG, PNG).', upload_to='servicios/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('precio', models.PositiveIntegerField(help_text='Precio del servicio en pesos chilenos (debe ser mayor a 0).', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['titulo'], name='titulo_idx')],
            },
        ),
    ]
